### ISSUE TITLE
Error qith geckodriver

### ISSUE THREAD

**Issue by 1621581** [Davide-1998/ilsole24ore_chart_data_download#1]
Ciao! Grazie per aver condiviso il tuo script, sto provando ad utilizzarlo per scaricare le news del sole 24 ore, ma ho dei problemi con gecko e selenium che non ho mai usato. Ho scaricato geckodriver da qua https://github.com/mozilla/geckodriver/releases, sapresti darmi qualche indicazione?

Grazie mille

Errore che ottengo:

Traceback (most recent call last):
  File "/home/lavi/anaconda3/envs/banca/lib/python3.8/site-packages/selenium/webdriver/common/service.py", line 72, in start
    self.process = subprocess.Popen(cmd, env=self.env,
  File "/home/lavi/anaconda3/envs/banca/lib/python3.8/subprocess.py", line 854, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "/home/lavi/anaconda3/envs/banca/lib/python3.8/subprocess.py", line 1702, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
PermissionError: [Errno 13] Permission denied: 'geckodriver'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "downloader.py", line 198, in <module>
    downloadData(urlToName(args.dUrl), args.dUrl,
  File "downloader.py", line 78, in downloadData
    driver = webdriver.Firefox(firefox_profile=profile, options=options)
  File "/home/lavi/anaconda3/envs/banca/lib/python3.8/site-packages/selenium/webdriver/firefox/webdriver.py", line 164, in __init__
    self.service.start()
  File "/home/lavi/anaconda3/envs/banca/lib/python3.8/site-packages/selenium/webdriver/common/service.py", line 86, in start
    raise WebDriverException(
selenium.common.exceptions.WebDriverException: Message: 'geckodriver' executable may have wrong permissions.

**Comment by Davide-1998** [comment]
Ciao, ho controllato il programma e sul mio dispositivo funziona correttamente.
Ho controllato comunque in internet e per risolvere il tuo problema propongono di controllare che il path che contiene il file .exe di gekodriver sia impostato correttamente.
Inoltre suggeriscono di assicurarti che gekodriver abbia i permessi per essere eseguito, risolvibile con '_chmod +x gekodriver.exe_' nel folder in cui il driver è contenuto.
Ho preso queste informazioni da qua: _https://stackoverflow.com/questions/46682841/selenium-common-exceptions-webdriverexception-message-geckodriver-executable_

Infine, ti informo che lo script che ho condiviso serve a scaricare ed elaborare i file .csv scaricabili dai grafici contenuti nella pagina web e non per altro.
